export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  files: Array<{
    path: string;
    content: string;
  }>;
  tags: string[];
}

export const defaultTemplates: ProjectTemplate[] = [
  // React Templates
  {
    id: 'react-ts',
    name: 'React + TypeScript',
    description: 'A modern React project with TypeScript, Vite, and Tailwind CSS',
    tags: ['react', 'typescript', 'frontend', 'vite', 'tailwind'],
    files: [
      {
        path: '/src/App.tsx',
        content: `import { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100">
      <h1 className="text-3xl font-bold mb-4">Vite + React + TypeScript</h1>
      <div className="p-6 bg-white rounded-lg shadow-md">
        <button 
          onClick={() => setCount((count) => count + 1)}
          className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        >
          Count is {count}
        </button>
        <p className="mt-4 text-gray-600">
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
    </div>
  )
}

export default App`
      },
      {
        path: '/vite.config.ts',
        content: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`
      },
      {
        path: '/package.json',
        content: `{
  "name": "my-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "@vitejs/plugin-react": "^4.2.0",
    "autoprefixer": "^10.4.0",
    "postcss": "^8.4.0",
    "tailwindcss": "^3.4.0",
    "typescript": "^5.0.0",
    "vite": "^5.0.0"
  }
}`
      },
      {
        path: '/tailwind.config.js',
        content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
      },
      {
        path: '/src/index.css',
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;`
      }
    ],
    tags: ['react', 'typescript', 'vite', 'tailwind']
  },
  {
    id: 'node-express',
    name: 'Node.js Express API',
    description: 'A basic Express.js API with TypeScript',
    files: [
      {
        path: '/src/index.ts',
        content: `import express from 'express';
import cors from 'cors';

export const app = express();
const port = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: 'Hello from Express!' });
});

app.listen(port, () => {
  console.log(\`🚀 Server is running on port \${port}\`);
});`
      },
      {
        path: '/tsconfig.json',
        content: `{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}`
      },
      {
        path: '/package.json',
        content: `{
  "name": "express-api",
  "version": "1.0.0",
  "description": "A basic Express.js API with TypeScript",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/index.js",
    "dev": "ts-node-dev --respawn --transpile-only src/index.ts"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "express": "^4.18.2"
  },
  "devDependencies": {
    "@types/cors": "^2.8.17",
    "@types/express": "^4.17.21",
    "@types/node": "^20.10.5",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.3.2"
  }
}`
      }
    ],
    tags: ['node', 'express', 'typescript', 'api']
  },
  {
    id: 'nextjs',
    name: 'Next.js App',
    description: 'A Next.js project with TypeScript and Tailwind CSS',
    files: [
      {
        path: '/pages/index.tsx',
        content: `import { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold text-center mb-8">
          Welcome to <a href="https://nextjs.org" className="text-blue-600 hover:underline">Next.js!</a>
        </h1>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <div className="p-6 bg-white rounded-lg shadow-md">
            <h2 className="text-xl font-semibold mb-2">Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </div>

          <div className="p-6 bg-white rounded-lg shadow-md">
            <h2 className="text-xl font-semibold mb-2">Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </div>

          <div className="p-6 bg-white rounded-lg shadow-md">
            <h2 className="text-xl font-semibold mb-2">Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </div>
        </div>
      </main>

      <footer className="text-center py-8 mt-16 border-t border-gray-200">
        <p>Powered by Next.js</p>
      </footer>
    </div>
  );
};

export default Home;`
      },
      {
        path: '/package.json',
        content: `{
  "name": "nextjs-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^20.10.5",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "autoprefixer": "^10.4.0",
    "eslint": "^8.0.0",
    "eslint-config-next": "^14.0.0",
    "postcss": "^8.4.0",
    "tailwindcss": "^3.4.0",
    "typescript": "^5.3.2"
  }
}`
      },
      {
        path: '/tailwind.config.js',
        content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
      },
      {
        path: '/postcss.config.js',
        content: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`
      }
    ],
    tags: ['nextjs', 'react', 'typescript', 'tailwind']
  },
  // Vue 3 with TypeScript
  {
    id: 'vue-ts',
    name: 'Vue 3 + TypeScript',
    description: 'Vue 3 with TypeScript, Vite and Composition API',
    tags: ['vue', 'typescript', 'frontend', 'vite'],
    files: [
      {
        path: '/src/App.vue',
        content: `<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <div class="flex flex-col items-center justify-center min-h-screen bg-gray-100">
    <h1 class="text-3xl font-bold mb-4">Vue 3 + TypeScript + Vite</h1>
    <div class="p-6 bg-white rounded-lg shadow-md">
      <button 
        @click="count++"
        class="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600"
      >
        Count is: {{ count }}
      </button>
      <p class="mt-4 text-gray-600">
        Edit <code>src/App.vue</code> to test HMR
      </p>
    </div>
  </div>
</template>

<style scoped>
/* Add your styles here */
</style>`
      },
      {
        path: '/vite.config.ts',
        content: `import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
})`
      },
      {
        path: '/package.json',
        content: `{
  "name": "vue-ts-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.3.4",
    "typescript": "^5.0.2",
    "vite": "^4.4.5",
    "vue-tsc": "^1.8.5"
  }
}`
      }
    ]
  },
  // Svelte with TypeScript
  {
    id: 'svelte-ts',
    name: 'Svelte + TypeScript',
    description: 'Svelte with TypeScript and Vite',
    tags: ['svelte', 'typescript', 'frontend', 'vite'],
    files: [
      {
        path: '/src/App.svelte',
        content: `<script lang="ts">
  let count: number = 0;
</script>

<main class="flex flex-col items-center justify-center min-h-screen bg-gray-100">
  <h1 class="text-3xl font-bold mb-4">Svelte + TypeScript</h1>
  <div class="p-6 bg-white rounded-lg shadow-md">
    <button 
      on:click={() => count++}
      class="px-4 py-2 bg-purple-500 text-white rounded hover:bg-purple-600"
    >
      Count is: {count}
    </button>
    <p class="mt-4 text-gray-600">
      Edit <code>src/App.svelte</code> to test HMR
    </p>
  </div>
</main>

<style>
  /* Add your styles here */
</style>`
      },
      {
        path: '/vite.config.ts',
        content: `import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

export default defineConfig({
  plugins: [svelte()],
})`
      },
      {
        path: '/package.json',
        content: `{
  "name": "svelte-ts-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^2.4.2",
    "svelte": "^4.2.7",
    "svelte-check": "^3.5.1",
    "typescript": "^5.0.0",
    "vite": "^4.4.5"
  }
}`
      }
    ]
  },
  // Python FastAPI Backend
  {
    id: 'fastapi',
    name: 'FastAPI Backend',
    description: 'A FastAPI backend with SQLAlchemy and Pydantic',
    tags: ['python', 'backend', 'fastapi', 'rest'],
    files: [
      {
        path: '/main.py',
        content: `from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional
import uvicorn

app = FastAPI()

class Item(BaseModel):
    name: str
    description: Optional[str] = None
    price: float
    tax: Optional[float] = None

items = []

@app.get("/")
async def read_root():
    return {"message": "Welcome to FastAPI!"}

@app.get("/items/", response_model=List[Item])
async def read_items():
    return items

@app.post("/items/", response_model=Item)
async def create_item(item: Item):
    items.append(item)
    return item

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)`
      },
      {
        path: '/requirements.txt',
        content: `fastapi==0.104.1
uvicorn==0.24.0
pydantic==2.4.2
python-dotenv==1.0.0`
      },
      {
        path: '/README.md',
        content: `# FastAPI Backend

A FastAPI backend with SQLAlchemy and Pydantic.

## Setup

1. Create a virtual environment:
   \`\`\`bash
   python -m venv venv
   source venv/bin/activate  # On Windows use: venv\Scripts\activate
   \`\`\`

2. Install dependencies:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`

3. Run the application:
   \`\`\`bash
   uvicorn main:app --reload
   \`\`\`

4. Open your browser to http://localhost:8000/docs to see the interactive API documentation.`
      }
    ]
  }
];
